# -*- coding: utf-8 -*-
# Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class BuriRacerTimerWidget(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setWindowFlags(QtCore.Qt.Window | QtCore.Qt.FramelessWindowHint)
        self.setAttribute(QtCore.Qt.WA_StyledBackground)

        radius = 20.0
        path = QtGui.QPainterPath()
        self.resize(400, 261)
        path.addRoundedRect(QtCore.QRectF(self.rect()), radius, radius)
        mask = QtGui.QRegion(path.toFillPolygon().toPolygon())
        self.setMask(mask)

        self.setObjectName("Timer")
        # self.resize(400, 261)
        self.setStyleSheet("background: #323437;"
                            "color: white;"
                            "border-radius: 20px solid #111111;"
                            "opacity: 100;"
                            "border: 10px #111111;")
        self.regex_validator = QtGui.QRegularExpressionValidator()
        self.regex_validator.setRegularExpression(QtCore.QRegularExpression(r"^[0-9]*$"))
        self.lineEdit = QtWidgets.QLineEdit(self)
        self.lineEdit.setValidator(self.regex_validator)
        self.lineEdit.returnPressed.connect(lambda: self.return_pressed())
        self.lineEdit.setGeometry(QtCore.QRect(70, 60, 251, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(20)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: #2A2C2F;\n"
"color: white;\n"
"border-radius: 9px;")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self)
        self.label.setDisabled(True)
        self.label.setGeometry(QtCore.QRect(70, 10, 281, 31))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self)
        self.textEdit.setReadOnly(True)
        self.textEdit.setDisabled(True)
        self.textEdit.setGeometry(QtCore.QRect(70, 110, 251, 81))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color: #323437; \n"
"color: white;\n"
"border-radius: 0px solid black;")
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(self)
        self.setWindowTitle('BuriRacer Time')
        QtCore.QMetaObject.connectSlotsByName(self)

        """---------------------CUSTOM-----------------"""
        self.__close_window = QtWidgets.QShortcut(QtGui.QKeySequence("Esc"), self)
        self.__close_window.activated.connect(lambda: self.close_window())
        self.show()

    def close_window(self):
        self.close()

    def retranslateUi(self, Timer):
        _translate = QtCore.QCoreApplication.translate
        Timer.setWindowTitle(_translate("Timer", "Form"))
        Timer.setWhatsThis(_translate("Timer", "<html><head/><body><p>background-color: #323437;</p><p>color: white;</p><p><br/></p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("Timer", "time"))
        self.label.setText(_translate("Timer", "Enter time in the line edit"))
        self.textEdit.setHtml(_translate("Timer", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'JetBrains Mono\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enter a non-zero, non-negative time. The time entered in line edit should be in seconds.</p></body></html>"))

    def return_pressed(self):
        int_text = self.lineEdit.text()
        self.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    # self = CustomWidget()  # QtWidgets.QWidget()
    ui = BuriRacerTimerWidget()
    # ui.setupUi(self)
    # self.show()
    sys.exit(app.exec_())
